---
- name: Hermes Station
  hosts: hermes
  gather_facts: no
  tasks: 
    #- setup:
      #- include: tasks/000_checkvars.yml
      #- include: tasks/010_sysbase.yml
      #- include: tasks/011_fstab.yml
      ##- include: tasks/020_network.yml
      - include: tasks/030_uucp.yml
      #- include: tasks/031_uucomp.yml
      #- include: tasks/040_uuardop.yml
      #- include: tasks/041_vara.yml
      ##- include: tasks/042_varaupd.yml
      # TODO verify permissions for sudo
      #- include: tasks/050_nginx.yml
      #- include: tasks/051_web_api.yml
      #- include: tasks/052_web_gui.yml
      #- include: tasks/053_web_downloads.yml
      # TODO test upload
      #- include: tasks/070_radio.yml
      #- include: tasks/071_radiotone.yml
      #- include: tasks/081_vnc.yml
      #- include: tasks/090_mail.yml
      #- include: tasks/091_roundcube.yml
      #- include: tasks/100_checklist.yml
      #- include: tasks/080_services.yml
      #- include: tasks/a_status.yml
