    - name: alsa modules and mixer settings
      block:

            - name: Alsa - intel-hda module settings 
              become: true
              copy:
                src: "conf/modprobe.d/intel_hda.conf"
                dest: "/etc/modprobe.d"
                owner: root
                group: root
                mode: '0744'

            - name: Alsa - module unload
              modprobe:
                name: snd-hda-intel
                state: absent

            - name: Alsa - module hda load
              modprobe:
                name: snd-hda-intel
                state: absent

            - name: System Base - copy volume settings 
              become: true
              copy:
                src: "conf/asound.state"
                dest: "/var/lib/alsa/asound.state"
                owner: root
                group: root
                mode: '0744'

            - name: System Base - alsactl restore
              become: true
              command: "alsactl restore"
              changed_when: True
            