    - name: Network setup

      block:

          - name: Network - copying interface.d files
            become: true
            copy:
              src: conf/interfaces.d
              dest: /etc/network
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - copying openvpn conf files
            become: true
            copy:
              src: "conf/{{ hostname }}.ovpn"
              dest: "/etc/openvpn/client/{{ hostname }}.conf"
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - copying dnsmasq.conf file
            become: true
            copy:
              src: "conf/dnsmasq.conf"
              dest: "/etc/"
              owner: root
              group: root
              mode: '0744'
              backup: yes
          
          
          
          - name: Network - setting files TODO
            command: "echo test"
            #ansible.builtin.lineinfile:
              #path: "{{ webpub_path }}/station-api/.env"
              #regexp: '^HERMES_INBOX='
              #line: "HERMES_INBOX={{ inbox_path }}"

          - name: Network - setting openVPN TODO
            command: "echo test"

          - name: Network - setting openVPN TODO
            command: "echo test"

          - name: Network - setting wifi TODO
            command: "echo test"