    - name: Network setup

      block:

          - name: Network - copying interface.d files
            become: true
            copy:
              src: conf/interfaces.d/
              dest: /etc/network/interfaces.d/
              owner: root
              group: root
              mode: '0744'
              backup: no

          - name: Network - openvpn setup - copying conf file
            become: true
            ignore_errors: yes
            copy:
              src: "conf/vpn/{{ inventory_hostname }}.ovpn"
              dest: "/etc/openvpn/client/{{ inventory_hostname }}.conf"
              owner: root
              group: root
              mode: '0744'
              backup: no

          - name: Network - wifi setup - service openvpn
            become: true
            ansible.builtin.service:
              name: openvpn-client@{{ inventory_hostname }}
              enabled: yes
              state: started

          - name: Network - wifi setup - wifi settings - antenna and pm
            become: true
            copy:
              src: "conf/modprobe.d/wifi.conf"
              dest: "/etc/modprobe.d"
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - wifi setup - depmod
            become: true
            command: "depmod -a"

          - name: Network - wifi setup - copying dnsmasq.conf file
            become: true
            copy:
              src: "conf/dnsmasq.conf"
              dest: "/etc/"
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - wifi setup - service dnsmasq
            become: true
            ansible.builtin.service:
              name: dnsmasq
              enabled: yes
              state: started

          - name: Network - wifi setup - copying dnsmasq.conf file
            become: true
            copy:
              src: "conf/hostapd.conf"
              dest: "/etc/hostapd/"
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - wifi setup - unmask hostapd
            become: true
            ansible.builtin.service:
              name: hostapd
              masked: no

          - name: Network - wifi setup - service hostpad
            become: true
            ansible.builtin.service:
              name: hostapd
              enabled: yes
              masked: no
              state: started
