    - name: Network setup

      block:

          - name: Network - copying interface.d files
            become: true
            copy:
              src: conf/interfaces.d/
              dest: /etc/network
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - openvpn setup - copying conf file
            become: true
            ignore_errors: yes
            copy:
              src: "conf/{{ hostname }}.ovpn"
              dest: "/etc/openvpn/client/{{ hostname }}.conf"
              owner: root
              group: root
              mode: '0744'
              backup: no

          - name: Network - wifi setup - service openvpn
            become: true
            ansible.builtin.service:
              name: openvpn-client@{{ hostname }}
              enabled: yes
              state: started


          - name: Network - wifi setup - wifi settings - antenna and pm
            become: true
            copy:
              src: "conf/modprobe.d/wifi.conf"
              dest: "/etc/modprobe.d"
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - wifi setup - depmod
            become: true
            command: "depmod -a"

          - name: Network - wifi setup - copying dnsmasq.conf file
            become: true
            copy:
              src: "conf/dnsmasq.conf"
              dest: "/etc/"
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - wifi setup - service dnsmasq
            become: true
            ansible.builtin.service:
              name: dnsmasq
              enabled: yes
              state: started

          - name: Network - wifi setup - copying dnsmasq.conf file
            become: true
            copy:
              src: "conf/hostapd.conf"
              dest: "/etc/hostapd/"
              owner: root
              group: root
              mode: '0744'
              backup: yes

          - name: Network - wifi setup - service hostpad
            become: true
            ansible.builtin.service:
              name: hostapd
              enabled: yes
              state: started

          - name: Network - setting files TODO
            command: "echo test"
            #ansible.builtin.lineinfile:
              #path: "{{ webpub_path }}/station-api/.env"
              #regexp: '^HERMES_INBOX='
              #line: "HERMES_INBOX={{ inbox_path }}"
