- name: Network setup
  block:
    - name: Network  install network packages and firmware
      become: true
      apt:
        install_recommends: yes
        state: present
        name:
          - hostapd
          - firmware-realtek
          - firmware-atheros
          - openvpn
          - dnsmasq
          - wireless-regdb
          - wireless-tools
          - wpasupplicant
          - dnsmasq
          - iw
          - linux-headers-amd64
      # when: vara_callsign == 'B0DE'
      # when: vara_callsign == 'B0DK' or hermes_callsign == 'B0DK-1'

    - name: Network  - git get driver for rtl8788eu
      git:
        repo: "https://github.com/lwfinger/rtl8188eu.git"
        clone: true
        dest: "{{ build_path }}/rtl8188eu/"
        version: v5.2.2.4
        force: true
    
    - name: Network -  build driver for rtl8788eu
      command: make
      args:
        chdir: "{{ build_path }}/rtl8188eu/"
      # when: vara_callsign == 'B0DE'

    - name: Network - install driver for rtl8788eu
      become: true
      command: make install
      args:
        chdir: "{{ build_path }}/rtl8188eu/"

    - name: Network - copying interface.d ethernet  enp3s0 file
      become: true
      copy:
        src: conf/interfaces.d/enp3s0
        dest: /etc/network/interfaces.d/enp3s0
        owner: root
        group: root
        mode: "0744"
        backup: false

    - name: Network - copying interface.d ethernet enp2s0 file
      become: true
      copy:
        src: conf/interfaces.d/enp2s0
        dest: /etc/network/interfaces.d/enp2s0
        owner: root
        group: root
        mode: "0744"
        backup: false

    - name: Network - remove wlp2s0 if exists
      become: true
      file:
        path: /etc/network/interfaces.d/wlp2s0
        state: absent

    - name: Network - gen template j2 wifi modprobe interface atheros
      become: true
      template:
        src: conf/interfaces.d/atheros.j2
        dest: /etc/network/interfaces.d/atheros
        owner: root
        mode: "0744"
        backup: false

    - name: Network - openvpn setup - copying conf file
      become: true
      ignore_errors: true
      copy:
        src: conf/vpn/{{ inventory_hostname }}.ovpn
        dest: /etc/openvpn/client/{{ inventory_hostname }}.conf
        owner: root
        group: root
        mode: "0744"
        backup: false

    - name: Network - openvpn setup - start client service 
      become: true
      ansible.builtin.service:
        name: openvpn-client@{{ inventory_hostname }}
        enabled: true
        state: started

    - name: Network - copy file for modprobe wifi.conf
      become: true
      template:
        src: conf/modprobe.d/wifi.conf
        dest: "/etc/modprobe.d/wifi.conf"
        mode: "0754"
        backup: false

    - name: Network - wifi setup - depmod
      become: true
      command: "depmod -a"

    - name: Network - wifi setup - copying dnsmasq.conf file
      become: true
      copy:
        src: conf/dnsmasq.conf
        dest: "/etc/"
        owner: root
        group: root
        mode: "0744"
        backup: false

    - name: Network - process template j2  for dnsmasq.conf
      become: true
      template:
        src: conf/dnsmasq.conf.j2
        dest: "/etc/dnsmasq.conf"
        owner: root
        group: root
        mode: "0744"
        backup: false

    - name: Network - wifi setup - service dnsmasq
      become: true
      ansible.builtin.service:
        name: dnsmasq
        enabled: yes
        state: started

    - name: Network - process template j2  for hostapd.conf file
      become: true
      template:
        src: conf/hostapd.conf.j2
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: "0744"
        backup: true

    - name: Network - wifi setup - unmask hostapd
      become: true
      ansible.builtin.service:
        name: hostapd
        masked: no

    - name: Network - wifi setup - service hostpad
      become: true
      ansible.builtin.service:
        name: hostapd
        enabled: yes
        masked: no
        state: started
