    - name: Network setup

      block:

          - name: Network - copying interface.d ethernet  file
            become: true
            copy:
              src: conf/interfaces.d/enp3s0
              dest: /etc/network/interfaces.d/en3ps0
              owner: root
              group: root
              mode: '0744'
              backup: false

          - name: Network - remove wlp2s0 if exists
            become: true
            file:
              src: conf/interfaces.d/wlps2s0
              type: absent

          - name: Network - copy wifi modprobe interface atheros
            become: true
            copy:
              src: conf/interfaces.d/atheros
              dest: /etc/interfaces/atheros"
              owner: root
              group: root
              mode: '0744'
              backup: false

          # - name: Network - openvpn setup - copying conf file
          #   become: true
          #   ignore_errors: true
          #   copy:
          #     src: conf/vpn/{{ inventory_hostname }}.ovpn
          #     dest: /etc/openvpn/client/{{ inventory_hostname }}.conf
          #     owner: root
          #     group: root
          #     mode: '0744'
          #     backup: false

          # - name: Network - wifi setup - service openvpn
          #   become: true
          #   ansible.builtin.service:
          #     name: openvpn-client@{{ inventory_hostname }}
          #     enabled: false
          #     state: started

          - name: Network - copy file template j2  for modprobe wifi.conf
            become: true
            template:
              src: conf/modprobe.d/wifi.conf.
              dest: "/etc/modprobe.d/wifi.conf"
              mode: '0754'
              backup: false

          - name: Network - wifi setup - depmod
            become: true
            command: "depmod -a"

          - name: Network - wifi setup - copying dnsmasq.conf file
            become: true
            copy:
              src: conf/dnsmasq.conf
              dest: "/etc/"
              owner: root
              group: root
              mode: '0744'
              backup: false

          - name: Network - process template j2  for dnsmasq.conf 
            become: true
            template:
              src: conf/dnsmasq.conf.j2
              dest: "/etc/dnsmasq.conf"
              owner: root
              group: root
              mode: '0744'
              backup: false

          - name: Network - wifi setup - service dnsmasq
            become: true
            ansible.builtin.service:
              name: dnsmasq
              enabled: yes
              state: started

          - name: Network - process template j2  for hostapd.conf file
            become: true
            template:
              src: conf/hostapd.conf.js
              dest: /etc/hostapd/hostapd.conf"
              owner: root
              group: root
              mode: '0744'
              backup: true

          - name: Network - wifi setup - unmask hostapd
            become: true
            ansible.builtin.service:
              name: hostapd
              masked: no

          - name: Network - wifi setup - service hostpad
            become: true
            ansible.builtin.service:
              name: hostapd
              enabled: yes
              masked: no
              state: started
