- name: uucp
  become_user: root
  block:

    - name: UUCP Setup - Install uucp system package
      become: true
      apt:
        name:
          - uucp 

    - name: UUCP - copy template configuration files
      become: true
      copy:
        src: conf/uucp/
        #dest: /etc/uucp/
        dest: /etc/uucp/
        directory_mode: true
        owner: uucp
        group: uucp
        mode: '0577'
        backup: yes

    - name: UUCP - setting nodename 
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/uucp/config"
        state: present
        regexp: "^nodename"
        #line: "$config['db_dsnw'] = 'sqlite:////tmp/roundcube.db';"
        line: "nodename {{ hostname }}"

    - name: UUCP - setting pubdir
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/uucp/config"
        state: present
        regexp: "^pubdir"
        line: "pubdir {{ inbox_path }}"