- name: uucpcomp setup
  block:
    - name: UUCOMP Setup - clone from git main
      git:
        repo: "https://github.com/DigitalHERMES/uucomp.git"
        clone: yes
        dest: "{{ build_path }}/uucomp/"
        version: main 
  
    - name: UUCOMP Setup - make  clean
      command: "make clean"
      args:
        chdir: "{{ build_path }}/uucomp/"
    
    - name: UUCOMP Setup - make 
      command: "make"
      args:
        chdir: "{{ build_path }}/uucomp/"

    - name: UUCOMP Setup - make  install
      become: true
      command: "make install"
      args:
        chdir: "{{ build_path }}/uucomp/"
    
    - name: UUCOMP Setup - Add an apt key
      become: true
      apt_key:
        url: http://packages.hermes.radio/hermes/rafael.key
        state: present

    - name: UUCOMP Setup - remove hermes-codecs legacy package if exists
      become: true
      apt:
        state: absent
        name:
        - hermes-codecs

    - name: UUCOMP Setup - add  hermes repository and update
      become: true
      apt_repository:
        repo: deb http://packages.hermes.radio/hermes/ bullseye main
        state: present 
        update_cache: yes 
        validate_certs: yes
        filename: hermes
    
    - name: UUCOOMP Setup - Installing debian packages 
      become: true
      apt:
        install_recommends: yes
        state: present
        name:
        - libb64-dev
        - ffmpeg
        - libmagic-dev
        - imagemagick 
        - vvenc
        - vvdec
        - mozjpeg
        - lpcnet


    - name: UUCOMP crontab - remove uucomp 
      become: true
      cron: 
        name: "uucomp 5 minutes"
        state: absent