- name: uucpcomp seutp
  block:
    - name: UUCOMP Setup - clone from git main
      git:
        repo: "git://github.com/DigitalHERMES/uucomp.git"
        clone: yes
        dest: "{{ build_path }}/uucomp/"
        version: HEAD
  
    - name: UUCOMP Setup - make  clean
      command: "make clean"
      args:
        chdir: "{{ build_path }}/uucomp/uucomp-rz1/"

    - name: UUCOMP Setup - make 
      command: "make"
      args:
        chdir: "{{ build_path }}/uucomp/uucomp-rz1/"

    - name: UUCOMP Setup - make 
      become: true
      command: "make install"
      args:
        chdir: "{{ build_path }}/uucomp/uucomp-rz1/"


        
