- name: uucpcomp seutp
  become_user: root
  block:

    - name: UUCOMP Setup - clone from git main
      git:
        repo: "git://github.com/DigitalHERMES/uucomp.git"
        clone: yes
        dest: "{{ build_path }}/uucomp/"
        version: HEAD

    - name: UUCOMP Setup -  install TODO
      command: "echo test"

        
