- name: uucpcomp setup
  block:
    - name: UUCOMP Setup - clone from git main
      git:
        repo: "git://github.com/DigitalHERMES/uucomp.git"
        clone: yes
        dest: "{{ build_path }}/uucomp/"
        version: main 
  
    - name: UUCOMP Setup - make  clean
      command: "make clean"
      args:
        chdir: "{{ build_path }}/uucomp/"
    
    - name: UUCOOMP Setup - Installing debian packages 
      become: true
      apt:
        install_recommends: yes
        state: present
        name:
        - libb64-dev
        - ffmpeg
        - libmagic-dev
        - imagemagick 

    - name: UUCOMP Setup - install  deb package hermes-codecs
      become: true
      command:  "dpkg -i contrib/hermes-codecs_1.0-2_all.deb"
      args:
        chdir: "{{ build_path }}/uucomp/"

    - name: UUCOMP Setup - make 
      command: "make"
      args:
        chdir: "{{ build_path }}/uucomp/"

    - name: UUCOMP Setup - make  install
      become: true
      command: "make install"
      args:
        chdir: "{{ build_path }}/uucomp/"


    - name: UUCOMP crontab - run uucomp every 5 minutes
      become: true
      cron: 
        name: "uucomp 5 minutes"
        state: absent

    - name: UUCOMP crontab - run uucomp every 5 minutes
      become: true
      cron: 
        name: "uucomp 5 minutes"
        user: root
        minute: "5"
        job: "compress.sh"
