- name: Rhizomatica UUARDOP
  become_user: root
  block:
  
    - name: UUARDOP - clone from github
      become: false
      git:
        repo: "git://github.com/DigitalHERMES/rhizo-uuardop.git"
        clone: yes
        dest: "{{ build_path }}/rhizo-uuardop/"
        version: HEAD
        
    - name: UUARDOP - build
      become: false
      command: make 
      args:
        chdir: "{{ build_path }}/rhizo-uuardop/"

    - name: UUARDOP - install host as station
      become: true
      command: make install
      args:
        chdir: "{{ build_path }}/rhizo-uuardop/"
      when: vara_callsign != hermes_callsign

    - name: UUARDOP - install host as a gateway
      become: true
      command: make install_gateway
      args:
        chdir: "{{ build_path }}/rhizo-uuardop/"
      when: vara_callsign == hermes_callsign

    - name: UUARDOP - service enable
      become: true
      ansible.builtin.service:
        name: uuardopd
        enabled: yes