    - name: VARA Install, 32 bit system base
      when: ansible_facts['distribution'] == 'Debian' and install_wine
      become: true
      become_user: root
      ignore_errors: yes
      block:
        - name: VARA Install - add 32bit arch
          become: true
          command: dpkg --add-architecture i386 

        - name: VARA Install - refresh apt 
          apt:
            update_cache: yes

        - name: VARA Install -  wine 64 and 32 bit packages
          become: true
          apt:
            install_recommends: no
            state: present
            name:
              - wine
              - wine32
              - wine64
              - winetricks
              - libwine
              - libwine:i386
              - fonts-wine

        - name: VARA Install - vara files
          copy:
            src: conf/VARA
            dest: "/home/{{ ansible_user }}/VARA"
            owner: "{{ ansible_user }}"
            group: hermes
            mode: '0577'
            backup: yes

        - name: VARA Install - setting callsign
          lineinfile:
            dest: "/home/{{ ansible_user }}/VARA/VARA.ini"
            regexp: "Callsign Licence 0="
            line: "Callsign Licence 0={{ vara_callsign }}"


        - name: VARA Install - setting license
          lineinfile:
            dest: "/home/{{ ansible_user }}/VARA/VARA.ini"
            regexp: "Registration Code="
            line: "Registration Code={{ vara_license }}"


        - name: VARA Install - setting retries to 5
          lineinfile:
            dest: "/home/{{ ansible_user }}/VARA/VARA.ini"
            regexp: "Retries="
            line: "Retries=5"

        - name: VARA Install - setting ALC Level to -3 
          lineinfile:
            dest: "/home/{{ ansible_user }}/VARA/VARA.ini"
            regexp: "ALC Drive Level="
            line: "ALC Drive Level=-3"


