    - name: VARA Install, 32 bit system base
      when: ansible_facts['distribution'] == 'Debian' and install_wine
      become: true
      become_user: root
      block:
        - name: VARA Install - add 32bit arch
          become: true
          command: dpkg --add-architecture i386 

        - name: VARA Install - refresh apt 
          apt:
            update_cache: yes

        - name: VARA Install -  wine 64 and 32 bit packages
          become: true
          apt:
            install_recommends: no
            state: present
            name:
              - wine
              - wine32
              - wine64
              - winetricks
              - libwine
              - libwine:i386
              - fonts-wine

        - name: VARA Install - test for vara install
          stat:
             path: "/home/{{ ansible_user }}/VARA"
          register: vara_exists
        
        - name: VARA Install - vara files
          when: not vara_exists.stat.exists
          copy:
            src: conf/VARA
            dest: "/home/{{ ansible_user }}/"
            owner: "{{ ansible_user }}"
            group: hermes
            mode: '0775'
            backup: no

        - name: VARA Install - VARA.ini
          copy: 
            src: conf/VARA.ini
            dest: "/home/{{ ansible_user }}/VARA/VARA.ini"
            backup: yes