---
- name: php and nginx install and setup
  become_user: root
  block:
    - name: Web Setup - PHP - install php-fpm, plugins and composer debian packages
      become: true
      apt:
        install_recommends: yes
        state: present
        name:
          - php-fpm
          - php-cli
          - php-curl
          - php-gd
          - php-mbstring
          - php-mysql
          - php-pear
          - php-soap
          - php-sqlite3
          - php-xml 
          - composer   

    - name: remove LPCNET install path
      file: 
        state: absent
        path: "{{ build_path }}/lpcnet"
        force: yes

    - name: Web Setup - PHP - Set date.timezone for FPM
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: "date.timezone ="
        line: "date.timezone = UTC"

    - name: Web Setup - PHP -  enabling mysql extension
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: ";extension=pdo_mysql"
        line: "extension=pdo_mysql"

    - name: Web Setup - PHP -  enabling sqlite extension
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: ";extension=sqlite3"
        line: "extension=sqlite3"

    - name: Web Setup - PHP -  enabling soap extension
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: ";extension=soap"
        line: "extension=soap"

    - name: Web Setup - PHP -  enabling mbstring extension
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: ";extension=mbstring"
        line: "extension=mbstring"

    - name: Web Setup - PHP -  enabling pear extension
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: ";extension=pear"
        line: "extension=pear"

    - name: Web Setup - PHP -  enabling gd extension
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: ";extension=gd"
        line: "extension=gd"

    - name: Web Setup - PHP -  enabling sqlite3 extension
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: ";extension=sqlite3"
        line: "extension=sqlite3"

    - name: Web Setup - PHP -  enabling max size of 100MB
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: "^post_max_size"
        line: "post_max_size = 100M"

    - name: Web Setup - PHP -  enabling upload max size of 100MB
      become: true
      lineinfile:
        backrefs: yes
        dest: /etc/php/7.4/fpm/php.ini
        regexp: "^upload_max_filesize"
        line: "upload_max_filesize= 100M"

    - name: Web Setup - PHP  - enabling service
      become: true
      ansible.builtin.service:
        name: php7.4-fpm
        enabled: yes


    - name: Web Setup - NGINX -  install nginx debian packages
      become: true
      apt:
        install_recommends: yes
        state: present
        name:
          - nginx

    - name: Web Setup - NGINX setup site hermes
      become: true
      copy:
        src: conf/nginx_hermes.conf 
        #dest: /etc/uucp/
        dest: /etc/nginx/sites-available/hermes.conf
        owner: www-data
        group: www-data
        mode: '0755'
        backup: yes

    - name: Web Setup - NGINX public folder permissions
      become: true
      file:
        path: "{{ webpub_path }}/html" 
        recurse: yes
        owner: "{{ ansible_user }}"
        group: "{{ www_group }}"
        mode: '0775'
        
        
    - name: Web Setup - NGINX - check for absent debian nginx default link
      become: true
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Web Setup - NGINX - Create a symbolic link to hermes.conf
      become: true
      ansible.builtin.file:
        src: /etc/nginx/sites-available/hermes.conf
        dest: /etc/nginx/sites-enabled/01-hermes.conf
        owner: www-data
        group: www-data
        state: link

    - name: Web Setup - NGINX - gen keys
      become: true
      command:
        openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=EQ/ST=a/L=a/O=Rhizomatica, Inc./OU=hermes/CN=hermes.radio"

    - name: Web Setup - NGINX - enable service
      become: true
      ansible.builtin.service:
        name: nginx
        enabled: yes

    #- name: Web Setup - NGINX - restart service
      # become: true
      # ansible.builtin.service:
      #   name: nginx
      #   state: restarted
