    - name: HERMES station-api backend software
      block:
        - name: HERMES API - install debian packages 
          become: true
          apt:
            install_recommends: yes
            state: present
            name:
              - mariadb-server
              - inotify-tools

        - name: HERMES API - Services install - mysql enable
          become: true
          ansible.builtin.service:
            name: mariadb
            enabled: yes
            state: started

        - name: HERMES API - Download HERMES station-api from github
          become: true
          git:
            repo: "git://github.com/DigitalHERMES/station-api.git"
            clone: yes
            dest: "{{ webpub_path }}/station-api"
            version: HEAD
            force: yes

        - name: HERMES API - setting permissions station
          become: true
          ansible.builtin.file:
            path: "{{ webpub_path }}/station-api"
            recurse: yes
            owner: hermes
            group: www-data
            mode: '0775'

        - name: HERMES API - Create a symbolic link for public html
          ansible.builtin.file:
            src: "{{ webpub_path }}/station-api/public"
            dest: "{{ webpub_path }}/html/api"
            owner: hermes
            group: www-data
            state: link

        - name: HERMES API - composer install
          command: "composer install"
          args:
            chdir: "{{ webpub_path }}/station-api"

        - name: HERMES API - check for .env
          stat:
            path: "{{ webpub_path }}/station-api/.env"
          register: api_env

        - name: HERMES API - .env exist?
          when: not api_env.stat.exists
          block: 
          - name: HERMES API - copy .env from .env.example 
            become: true
            command: "cp .env.example .env"
            args:
              chdir: "{{ webpub_path }}/station-api/"

        - name: HERMES API - copy  .env from template
          when: not api_env.stat.exists
          become: true
          command: "cp .env.example .env"
          args:
            chdir: "{{ webpub_path }}/station-api/"

        - name: HERMES API - gen app key
          when: not api_env.stat.exists
          shell: "date | openssl passwd -6 -stdin "
          register: app_key
        
        - name: HERMES API - setting .env APP_KEY
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^APP_KEY='
            line: "APP_KEY= {{ app_key.stdout }}"

        - name: HERMES API - setting .env HERMES_INBOX with {{ inbox_path }}
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^HERMES_INBOX='
            line: "HERMES_INBOX={{ inbox_path }}"

        - name: HERMES API - setting .env HERMES_INBOX with {{ ubitx_client }}
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path}}/.env"
            regexp: '^HERMES_TOOL='
            line: "HERMES_TOOL={{ ubitx_client }}"

        - name: HERMES API - setting .env DB_CONNECTION with mysql
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^DB_CONNECTION='
            line: "DB_CONNECTION=mysql"


        - name: HERMES API - setting .env DB_HOST  with localhost
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^#DB_HOST='
            line: "DB_HOST=127.0.0.1"

        - name: HERMES API - setting .env DB_PORT with 3306
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^#DB_PORT'
            line: "DB_PORT=3306"

        - name: HERMES API - setting .env DB_DATABASE 
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^#DB_DATABASE='
            line: "DB_DATABASE={{ hermes_db }}"

        - name: HERMES API - setting .env DB_USERNAME
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^#DB_USERNAME='
            line: "DB_USERNAME={{ hermes_db_user }}"

        - name: HERMES API - setting .env DB_PASSWORD
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^#DB_PASSWORD='
            line: "DB_PASSWORD={{ hermes_db_password }}"

        - name: HERMES API - setting .env EMAILAPI_LOC
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^#HERMES_EMAILAPI_LOC='
            line: "HERMES_EMAILAPI_LOC = https://localhost:8080/remote/index.php"

        - name: HERMES API - setting .env EMAILAPI_LOC
          when: not api_env.stat.exists
          ansible.builtin.lineinfile:
            path: "{{ webapi_path }}/.env"
            regexp: '^#HERMES_EMAILAPI_URI='
            line: "HERMES_EMAILAPI_URI = https://localhost:8080/remote"

        - name: HERMES API - create database
          become: true
          community.mysql.mysql_db:
            login_unix_socket: /var/run/mysqld/mysqld.sock
            name: hermes
            state: present

        - name: HERMES API - create database user
          become: true
          community.mysql.mysql_user:
            login_unix_socket: /var/run/mysqld/mysqld.sock
            name: "{{ hermes_db_user }}"
            password: "{{ hermes_db_password }}"
            priv: "{{ hermes_db }}.*:ALL"
            state: present

        - name: HERMES API - create database tables
          command: "php artisan migrate:refresh"
          args:
            chdir: "{{ webpub_path }}/station-api/"
                
        - name: HERMES API - populate database tables
          command: "php artisan db:seed"
          args:
            chdir: "{{ webpub_path }}/station-api/"
                
        - name: HERMES API - create user admin TODO 
          command: echo TODO
          args:
            chdir: "{{ webpub_path }}/station-api/"

        - name: HERMES API - copy hmp system service
          become: true
          copy:
            src: "conf/services/hmp.service"
            dest: "/etc/systemd/system/"
            owner: root
            group: root
            mode: '0766'
            backup: yes

        - name: HERMES API - enable hmp service
          become: true
          ansible.builtin.service:
            name: hmp
            enabled: yes

