    - name: HERMES web gui angular frontend software
      block:
        #- name: Download HERMES web gui angular from github
          #become: true
          #git:
            #repo: "git://github.com/DigitalHERMES/angular.git"
            #clone: yes
            #dest: "{{ build_path }}/angular"
            #version: HEAD
        - name: HERMES web gui angular linux packages
          apt:
            install_recommends: yes
            state: present
            name:
              - nodejs
              - npm
        - name: HERMES web gui install node modules 
          command: "npm i"
          args:
            chdir: "{{ build_path }}/angular/"
        #- name: HERMES web gui install node modules 2
          #become: true
          #npm:
            #path: "{{ build_path }}/angular/"
            #state: latest
        - name: HERMES web gui build 
          command: "npm run build"
          args:
            chdir: "{{ build_path }}/angular/"

        - name: HERMES web gui test angular
          become: true
          command: "ls {{ build_path }}/angular/dist/hermes/ "
          args:
            chdir: "{{ build_path }}/angular/"

        - name: HERMES web gui install angular english
          become: true
          command: "cp -a dist/hermes/en-US {{ webpub_path }}/html"
          args:
            chdir: "{{ build_path }}/angular/"

        - name: HERMES web gui install angular spanish
          become: true
          command: "cp -a dist/hermes/es {{ webpub_path }}/html"
          args:
            chdir: "{{ build_path }}/angular/"

        - name: HERMES web gui install angular spanish
          become: true
          command: "cp -a dist/hermes/pt {{ webpub_path }}/html"
          args:
            chdir: "{{ build_path }}/angular/"