    - name: HERMES web gui angular frontend software
      block:
        - name: Download HERMES web gui angular from github
          git:
            repo: "git://github.com/DigitalHERMES/angular.git"
            clone: yes
            dest: "{{ build_path }}/angular"
            version: HEAD
            force: yes

        - name: HERMES web gui - angular linux packages
          become: true
          apt:
            install_recommends: yes
            state: present
            name:
              - nodejs
              - npm

        - name: Hermes web gui - setting global_constants.ts
          become: true
          ansible.builtin.lineinfile:
            path: "{{ build_path }}/angular/src/app/global-constants.ts"
            state: present
            regexp: "^   public static apiURL"
            line: "   public static apiURL = '/api';"
            #validate: /usr/sbin/visudo -cf %s

        - name: HERMES web gui -  install node modules 
          command: "npm i"
          args:
            chdir: "{{ build_path }}/angular/"
        
        #- name: HERMES web gui install node modules 2
          #become: true
          #npm:
            #path: "{{ build_path }}/angular/"
            #state: latest
        - name: HERMES web gui - build 
          command: "npm run build"
          args:
            chdir: "{{ build_path }}/angular/"

        - name: HERMES web gui - install files
          become: true
          copy:
            src:  "{{ build_path }}/angular/dist/hermes/"
            dest: "{{ webpub_path }}/html"
            owner: hermes
            group: www-data
            mode: '0766'
            remote_src: yes
            backup: yes