    - name: HERMES web gui angular frontend software
      block:
        - name: Download HERMES web gui angular from github
          git:
            repo: "git://github.com/DigitalHERMES/angular.git"
            clone: yes
            dest: "{{ build_path }}/angular"
            version: "master"
            force: yes

        - name: HERMES web gui - angular linux packages
          become: true
          apt:
            install_recommends: yes
            state: present
            name:
              - nodejs
              - npm

        - name: HERMES web gui -  update node modules 
          command: "npm update --force"
          args:
            chdir: "{{ build_path }}/angular/"

        - name: HERMES web gui -  install node modules 
          command: "npm i"
          args:
            chdir: "{{ build_path }}/angular/"
        
        #- name: HERMES web gui install node modules 2
          #become: true
          #npm:
            #path: "{{ build_path }}/angular/"
            #state: latest
        - name: HERMES web gui - build 
          command: "npm run build"
          args:
            chdir: "{{ build_path }}/angular/"

        - name: HERMES web gui - install files
          become: true
          copy:
            src:  "{{ build_path }}/angular/dist/hermes/"
            dest: "{{ webpub_path }}/html"
            owner: hermes
            group: www-data
            mode: '0766'
            remote_src: yes
            backup: no

        - name: HERMES API reforce Web Setup - NGINX public folder permissions
          become: true
          file:
            path: "{{ webpub_path }}/html" 
            recurse: yes
            owner: "{{ ansible_user }}"
            group: "{{ www_group }}"
            mode: '0775'