    - name: HERMES web extra downloads
      vars:
        - version: 1.26.0
        - apk_version: 1.28.3
        - url: https://hermes.radio/deltachat
        - urlorig: https://download.delta.chat/desktop/v{{ version}}
    
      block:
        - name: create download path
          become: true
          file: 
            path: "{{ webgui_path }}/downloads/"
            owner: "{{ ansible_user }}"
            group: "{{ www_group }}"
            state: directory

        - name: Download deltachat app file for Debian GNU Linux (deb)
          get_url: 
            url: "{{ url }}/deltachat-desktop_{{ version }}_amd64.deb"
            # updated for 1.26
            checksum: "sha512:957cc5efab62f7c2bc9ab69e48a278118b9e1c33cf31b21fbb7dd06a507b57a940ad472b0bd1c76bda0fdaa02500d40aec46413666c04ce9b7551ec998c64e67"
            dest: "{{ webgui_path }}/downloads/deltachat-desktop_{{ version }}_amd64.deb"

        - name: Symbolic link to deltachat file for Debian GNU Linux (deb)) 
          file:
            src: "{{ webgui_path }}/downloads/deltachat-desktop_{{ version }}_amd64.deb"
            dest: "{{ webgui_path }}/downloads/deltachat.deb"
            state: link
            force: yes

        - name: Download deltachat app file for macosx (dmg)
          get_url: 
            url: "{{ url }}/DeltaChat-{{ version }}.dmg"
            # updated for 1.26
            dest: "{{ webgui_path }}/downloads/DeltaChat-{{ version }}.dmg"

        - name: Symbolic link to deltachat file for macosx (dmg)) 
          file:
            src: "{{ webgui_path }}/downloads/DeltaChat-{{ version }}.dmg"
            dest: "{{ webgui_path }}/downloads/deltachat.dmg"
            state: link
            force: yes

        - name: Download deltachat app file for windows (exe)
          get_url:
            url: "{{ url }}/DeltaChat%20Setup%20{{ version }}.exe"
            checksum: "sha512:9c0898bf51a1f6779646b76babf9f0bfd973a525865ada83fbf97d61bc88094f1870b676db5384e858dd49e22117b5f51b519dd81d7fb27a30d8837b834cd23b"
            dest: "{{ webgui_path }}/downloads/DeltaChat_Setup-{{ version }}.exe"

        - name: Symbolic link to deltachat file for windows (exe)
          file:
            src: "{{webgui_path }}/downloads/DeltaChat_Setup-{{ version }}.exe"
            dest: "{{ webgui_path }}/downloads/deltachat.exe"
            state: link
            force: yes

        - name: Download deltachat app file for android (apk)
          get_url:
            # url: "https://download.delta.chat/android/deltachat-gplay-release-{{ apk_version }}.apk"
            url: "{{ url }}/deltachat-gplay-release-{{ apk_version }}.apk"
            checksum: "sha512:db32b8f649ef953e09f1891051ad986e544ca519a6f6d8a98b397b8db1ccb8c29633f601046e958e1d84d05c302b19932989f4b5b7b9cb757370519209ce9032"
            dest: "{{ webgui_path }}/downloads/deltachat-gplay-release-{{ apk_version }}.apk"

        - name: Symbolic link to deltachat file for android (apk)
          file:
            src: "{{webgui_path}}/downloads/deltachat-gplay-release-{{ apk_version }}.apk"
            dest: "{{ webgui_path }}/downloads/deltachat.apk"
            state: link
            force: yes