- name: LPCNet setup
  become_user: root
  block:
    - name: LPCNet Setup - clone from git main
      git:
        repo: "git://github.com/mozilla/LPCNet.git"
        clone: yes
        dest: "{{ build_path }}/lpcnet/"
        version: HEAD

    - name: LPCNet Setup - autogen.sh
      command: "./autogen.sh"
      args:
        chdir: "{{ build_path }}/lpcnet/"

    - name: LPCNet Setup - configure 
      command: "./configure --prefix=/usr"
      args:
        chdir: "{{ build_path }}/lpcnet/"

    - name: LPCNet Setup - make
      command: "make"
      args:
        chdir: "{{ build_path }}/lpcnet/"

    - name: LPCNet Setup - make install
      become: true
      command: "make install"
      args:
        chdir: "{{ build_path }}/lpcnet/"