- name: Radio setup 
  block:
    - name: Radio Setup - clone firmware from git main
      git:
        repo: "https://github.com/DigitalHERMES/ubitxv6.git"
        clone: yes
        force: yes
        dest: "{{ build_path }}/ubitxv6/"
        version: origin/master 

    - name: Radio Setup - ubitxv6 build
      command: "make"
      args:
        chdir: "{{ build_path }}/ubitxv6/"

    - name: Radio Setup - ubitxv6  install 
      become: true
      command: "make install"
      args:
        chdir: "{{ build_path }}/ubitxv6/"

    - name: Radio Setup - ubitx daemon-reload and stop service ubitx
      become: true
      ansible.builtin.service:
        name: ubitx
        daemon_reload: yes
        enabled: yes
        state: stopped

    - name: Radio Setup - ubitxv6 radio firmware update 
      become: true
      command: "make ispload"
      args:
        chdir: "{{ build_path }}/ubitxv6/firmware"

    - name: Radio Setup - ubitx daemon-reload and service enable
      become: true
      ansible.builtin.service:
        name: ubitx
        enabled: yes
        state: started
