- name: alsatonic setup 
  block:
    - name: alsatonic depends- Installing debian packages 
      become: true
      apt:
        install_recommends: yes
        state: present
        name:
        - libasound2-dev

    - name: alsatonic Setup - clone firmware from git main
      git:
        repo: "git://github.com/DigitalHERMES/alsatonic.git"
        clone: yes
        force: yes
        dest: "{{ build_path }}/alsatonic/"
        version: origin/master 

    - name: alsatonic Setup - build
      command: "make"
      args:
        chdir: "{{ build_path }}/alsatonic/"

    - name: alsatonic Setup - install 
      become: true
      command: "make install"
      args:
        chdir: "{{ build_path }}/alsatonic/"

