- name: Radio  settings 
  block:

    - name: Radio - set frequency
      become: true
      command: "ubitx_client -c set_frequency -a 5085000"

    - name: Radio - set mode
      become: true
      command: "ubitx_client -c set_mode -a USB"

    - name: Radio - set defaults
      become: true
      command: "ubitx_client -c set_radio_defaults"
    