
    - name: Services install - mysql enable
      become: true
      ansible.builtin.service:
        name: mariadb
        enabled: yes
        state: started

    - name: Services install - postfix enable TODO
      become: true
      ansible.builtin.service:
        name: postfix
        enabled: yes
        state: started

    - name: Services install - copy ubitx service
        become: true
        copy:
          src: "conf/services/ubitx.service"
          dest: "/etc/systemd/system/"
          owner: root
          group: root
          mode: '0766'
          backup: yes

    - name: Services install - ubitx service enable
      become: true
      ansible.builtin.service:
        name: ubitx
        enabled: yes
        state: started
 
    - name: Services install - copy hmp service
        become: true
        copy:
          src: "conf/services/ubitx.service"
          dest: "/etc/systemd/system/"
          owner: root
          group: root
          mode: '0766'
          backup: yes

    - name: Services install - hmp service enable
      become: true
      ansible.builtin.service:
        name: hmp
        enabled: yes
        state: started
 