
    - name: Services install - mysql enable
      become: true
      ansible.builtin.service:
        name: mariadb
        enabled: yes
        state: started

    - name: Services install - postfix enable TODO
      become: true
      ansible.builtin.service:
        name: postfix
        enabled: yes
        state: started

