    - name: VNC service 
      block:
      - name: VNC service - Installing debian packages 
        become: true
        apt:
          install_recommends: no
          state: present
          name:
            - tigervnc-standalone-server
      - name: VNC service - Create a user path if it does not exist
        ansible.builtin.file:
          path: "/home/{{ ansible_user }}/.vnc/"
          state: directory
          mode: '0750'

      - name: VNC service - generatepasswd 
        shell: "echo hermes | vncpasswd -f"
        register: vncpass
      
      - name: VNC service - debug pass
        debug: 
          msg= "{{ vncpass.stdout }}"

      - name: VNC service - passwd to file
        copy:
          content: "{{ vncpass.stdout }}"
          dest: "/home/{{ ansible_user }}/.vnc/passwd"
          mode: '0600'

      - name: VNC service - copy xstartup
        copy:
          src: "conf/vnc/xstartup"
          dest: "/home/{{ ansible_user }}/.vnc/xstartup"
          owner: "{{ ansible_user }}"
          group: hermes
          mode: '0766'
          backup: yes

      - name: VNC service - copy vnc service
        become: true
        copy:
          src: "conf/services/vnc.service"
          dest: "/etc/systemd/system/"
          owner: root
          group: root
          mode: '0766'
          backup: yes

      - name: VNC service -  service enable 
        become: true
        ansible.builtin.service:
          name: vnc
          enabled: yes
          state: started