    - name: VNC service 
      block:
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: "/home/{{ ansible_user }}/.vnc/"
          state: directory
          mode: '0750'

      - name: VNC System Base - copy passwd  TODO Check
        copy:
          src: "conf/vnc/passwd"
          dest: "/home/{{ ansible_user }}/.vnc/passwd"
          owner: "{{ ansible_user }}"
          group: hermes
          mode: '0766'
          backup: yes

      - name: VNC System Base - copy xstartup
        copy:
          src: "conf/vnc/xstartup"
          dest: "/home/{{ ansible_user }}/.vnc/xstartup"
          owner: "{{ ansible_user }}"
          group: hermes
          mode: '0766'
          backup: yes

      - name: VNC System Base - copy vnc service
        become: true
        copy:
          src: "conf/services/vnc.service"
          dest: "/etc/systemd/system/"
          owner: root
          group: root
          mode: '0766'
          backup: yes

      - name: VNC System Base -  vnc
        become: true
        ansible.builtin.service:
          name: vnc
          enabled: yes
          state: started
                
              
