---
- name: ISP Config 
  become_user: root
  block:
    - name: Mail - install packages
      become: true
      apt:
        install_recommends: no
        state: present
        name:
          - postfix
          - postfix-mysql
          - postfix-doc
          - postgrey
          - spamassassin
          - ntp
          - mariadb-client
          - binutils
          - mariadb-server
          - openssl
          - getmail
          - rkhunter
          - binutils
          - dovecot-imapd
          - dovecot-pop3d
          - dovecot-mysql
          - dovecot-sieve
          - dovecot-lmtpd
          - amavisd-milter
          - clamav-freshclam
          - clamav
          - clamav-daemon
          - clamav-unofficial-sigs

    - name:  Mail - ISPconfig download and extract tarball
      unarchive:
        src: 'https://ispconfig.org/downloads/ISPConfig-3.2.5.tar.gz'
        dest: '{{ build_path }}'
        remote_src: yes

    - name: Mail - ISPconfig patch debian100.conf.php 
      become: true
      ansible.builtin.replace:
        path: "{{ build_path }}/ispconfig3_install/install/dist/conf/debian100.conf.php"
        regexp: "7.3"
        replace: "7.4"

    - name: Mail - generate ispconfig.ini template on remote host
      template:
        src: "./conf/ispconfig.ini.j2"
        dest: "{{ build_path }}/ispconfig3_install/install/autoinstall.ini"
        mode: '0754'

    - name: Mail - check if ISPConfig is already installed
      stat:
        path: /usr/local/ispconfig
      register: ispconfig_installed

    #- name: Mail -  Start ISPConfig Installation
      #become: true
      #command: "php -q install.php --autoinstall=autoinstall.ini"
      #args:
        #chdir: "{{ build_path }}/ispconfig3_install/install/"
      #when: not ispconfig_installed.stat.exists
    
    - block:
      - name: Mail - manual installation
        debug:
          msg: Do the manual installation of ispconfig 

      - meta: end_play
      when: not ispconfig_installed.stat.exists

    - name: Mail - set default_transport to uucp:gw
      become: true
      ansible.builtin.lineinfile:
        path: "/etc/postfix/main.cf"
        backrefs: yes
        state: present
        regexp: "^relayhost"
        line: "default_transport = uucp:gw"

    - name: Mail - disable filters
      become: true
      ansible.builtin.lineinfile:
        backrefs: yes
        path: "/etc/postfix/main.cf"
        state: present
        regexp: "^content_filter*"
        #regexp: "^content_filter = lmtp:[127.0.0.1]:10024"
        line: "#content_filter = lmtp:[127.0.0.1]:10024"

    - name: Mail - comment receive_override 
      become: true
      ansible.builtin.lineinfile:
        backrefs: yes
        path: "/etc/postfix/main.cf"
        state: present
        regexp: "^receive_override_options = no_address_mappings"
        line: "#receive_override_options = no_address_mappings"

    - name: Mail - allow all domains
      become: true
      ansible.builtin.lineinfile:
        backrefs: yes
        path: "/etc/postfix/main.cf"
        state: present
        regexp: "^smtpd_recipient_restrictions*"
        line:  "smtpd_recipient_restrictions = permit_mynetworks, reject_unlisted_recipient, check_recipient_access proxy:mysql:/etc/postfix/mysql-verify_recipients.cf, permit_sasl_authenticated, reject_non_fqdn_recipient, reject_unauth_destination, check_recipient_access proxy:mysql:/etc/postfix/mysql-virtual_recipient.cf, check_policy_service unix:private/quota-status"

    - name: Mail - set no run uucico after uucp command
      become: true
      ansible.builtin.lineinfile:
        backrefs: yes
        path: "/etc/postfix/master.cf"
        state: present
        regexp: "^  flags=Fqhu user=uucp*"
        line: "  flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)"

    - name: Mail - tag_as_foreign.re  10024
      become: true
      ansible.builtin.lineinfile:
        backrefs: yes
        path: "/etc/postfix/tag_as_foreign.re"
        state: present
        regexp: "^/^/ FILTER*"
        line: "/^/ FILTER lmtp:[127.0.0.1]:10024"

    - name: Mail - disable clamav-daemon service
      become: true
      ansible.builtin.service:
        name: clamav-daemon
        state: stopped
        enabled: no

    - name: Mail - disable clamav-freshclam
      become: true
      ansible.builtin.service:
        name: clamav-daemon
        state: stopped
        enabled: no

    - name: Mail - restart postfix 
      become: true
      ansible.builtin.service:
        name: postfix
        state: restarted
        enabled: yes
