build_path: /home/hermes/install
webpub_path: /var/www
webapi_path: "{{ webpub_path }}/station-api"
inbox_path: "{{ webapi_path }}/storage/app/inbox"
webgui_path: "{{ webpub_path }}/html"
install_wine: true
ubitx_client: "/usr/bin/ubitx_client"
hermes_db: hermes
hermes_db_user: hermes
hermes_db_password: db_hermes
install_uuardop_path: /tmp/build
www_group: www-data
ansible_python_interpreter: /usr/bin/python3
ansible_user: hermes
isp_user: apiadmin
isp_pass: hermescaduceu
#vara_callsign: 
#vara_license: 

